; Script generated by Sheheryar Ali for BYLD Core
; This script creates a single-file installer that deploys to AppData\Local.

#define MyAppName "BYLD Core PC Stats Monitor"
#define MyAppPublisher "BYLD Core"
#define MyAppExeName "PcStatsMonitor.exe"
#define MyAppVersion "1.0.0"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
AppId={{9A97C51E-3107-430E-8EB3-58D0EFEB179D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppPublisher}\{#MyAppName}
; "x64os" = native 64-bit Windows. The old "x64" spelling is deprecated and the compiler
; substitutes x64os anyway; naming it explicitly removes the warning. Not "x64compatible",
; which would also allow ARM64 emulation where the hardware driver cannot work.
ArchitecturesAllowed=x64os
ArchitecturesInstallIn64BitMode=x64os
DefaultGroupName={#MyAppPublisher}
DisableProgramGroupPage=yes
OutputDir=InstallerOutput
OutputBaseFilename=BYLD_PC_Stats_Monitor_Setup
SetupIconFile=Assets\byld-icon.ico
Compression=lzma
SolidCompression=yes
; Modern, per-monitor-DPI-aware wizard. The task/launch checkboxes are restored
; (round 18, item 2) — the client wants the options back, just not clipped.
;
; CLIPPING NOTES (client rounds 16-19): the task checkbox renders as a sliver with no
; label on his 5120x2880 display.
;   * WizardResizable was REMOVED - Inno Setup 7 reports it as obsolete and ignores it.
;   * WizardSizePercent=120,120 was REMOVED - enlarging the wizard is a prime suspect for
;     the mis-measured checkbox, so this returns the pages to their natural size.
;   * BUILD WITH THE STABLE INNO SETUP 6 COMPILER, NOT the 7.0 preview that is also on this
;     machine. A preview compiler was the remaining suspect for the undersized checkbox glyph
;     at 200% DPI. Use:
;         "%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe" PcStatsMonitor_Installer.iss
;     (Inno Setup 6.7.3, installed via winget as JRSoftware.InnoSetup.)
WizardStyle=modern
; Skips the "Ready to Install" summary, which appeared as a large grey review box
; (client round 19, item 2). Install starts straight after the task selection.
DisableReadyPage=yes
; "PrivilegesRequired=admin" ensures the installer and its launched app have elevation.
PrivilegesRequired=admin
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main application files
; Run 'dotnet publish -c Release -r win-x64 --self-contained' before compiling this script
Source: "d:\Github Repos\PC-Stats-Monitor\bin\Release\net10.0-windows\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; PawnIO installer — bundled DIRECTLY from the repo root, independent of the .NET
; publish output. Place the official PawnIO_setup.exe (https://pawnio.eu/) at the
; repo root. The app runs this on first launch to install the signed driver;
; skipifsourcedoesntexist keeps the compile working if the file is absent.
Source: "d:\Github Repos\PC-Stats-Monitor\PawnIO_setup.exe"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist

; OpenRGB bundled server — portable binaries in Tools folder
; Download from https://openrgb.org/releases.html (Windows portable ZIP)
; onlyifdoesntexist: OpenRGB ships its OWN WinRing0 kernel driver. Once loaded it
; locks OpenRGB\WinRing0x64.sys, so replacing it on an upgrade fails with
; "Access is denied". These files are static across our builds, so we keep the
; existing copy rather than fighting the lock.
Source: "d:\Github Repos\PC-Stats-Monitor\Tools\OpenRGB Windows 64-bit\*"; DestDir: "{app}\OpenRGB"; Flags: recursesubdirs createallsubdirs skipifsourcedoesntexist onlyifdoesntexist

[InstallDelete]
; Remove the old root-level WinRing0x64.sys shipped by pre-PawnIO builds. It is no
; longer used (LibreHardwareMonitor reads hardware through PawnIO now), and leaving
; it behind is dead weight.
Type: files; Name: "{app}\WinRing0x64.sys"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; WorkingDir: "{app}"

[Run]
; Install the PawnIO driver silently BEFORE the app first launches. PawnIO is the
; Microsoft-signed, sandboxed driver LibreHardwareMonitor uses to read CPU MSRs
; and the motherboard Super I/O. The app also self-installs it on first run
; (Services/PawnIoDriverService.cs), so this step is a no-op if PawnIO is present.
Filename: "{app}\PawnIO_setup.exe"; Parameters: "-install -silent"; Flags: runhidden waituntilterminated; Check: PawnIoSetupNeeded; StatusMsg: "Installing PawnIO hardware driver..."
; NOTE: OpenRGB is NOT started here — the app manages the OpenRGB server itself.
; Launch main application (finish-page checkbox restored — round 18, item 2)
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent shellexec; WorkingDir: "{app}"

[UninstallRun]
; Kill the app and OpenRGB, then stop OpenRGB's WinRing0 kernel service so its
; .sys unlocks and the OpenRGB folder can be removed. PawnIO is a shared, signed
; driver used by other tools (LibreHardwareMonitor, Fan Control, OpenRGB) and is
; intentionally left installed.
Filename: "taskkill.exe"; Parameters: "/F /IM PcStatsMonitor.exe"; Flags: runhidden; RunOnceId: "KillApp"
Filename: "taskkill.exe"; Parameters: "/F /IM OpenRGB.exe"; Flags: runhidden; RunOnceId: "KillOpenRGB"
Filename: "sc.exe"; Parameters: "stop WinRing0_1_2_0"; Flags: runhidden; RunOnceId: "StopWinRing0"
; Remove the logon scheduled task the app registers (auto-start with highest privileges).
Filename: "schtasks.exe"; Parameters: "/Delete /TN ""BYLDCore_PCStatsMonitor_Startup"" /F"; Flags: runhidden; RunOnceId: "DeleteStartupTask"

[UninstallDelete]
; Files created at runtime (not in the install log) that would otherwise
; keep the install folder alive after uninstall.
Type: filesandordirs; Name: "{app}\OpenRGB"
Type: filesandordirs; Name: "{app}\settings"
Type: filesandordirs; Name: "{app}\logs"
Type: filesandordirs; Name: "{app}\Profiles"
Type: files; Name: "{app}\theme.json"
Type: dirifempty; Name: "{app}"
Type: dirifempty; Name: "{autopf}\{#MyAppPublisher}"

[Code]
// This section must exist: Inno Setup raises "Internal error: PathRedir: Not
// initialized" on every uninstall log entry when the script has no [Code]
// section (bug present in the 7.0 previews).
function InitializeUninstall(): Boolean;
begin
  Result := True;
end;

// Install PawnIO only when the bundled setup is present AND PawnIO is not already
// registered — so an upgrade on a machine that already has PawnIO skips the reinstall.
function PawnIoSetupNeeded: Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\PawnIO_setup.exe')) and
            not RegKeyExists(HKLM, 'SYSTEM\CurrentControlSet\Services\PawnIO');
end;

// On uninstall, also remove PawnIO — the driver this app installs, via its own
// installer CLI (PawnIO_setup.exe -uninstall -silent). The setup is still present
// in {app} at this step (files are removed afterwards). PawnIO is a SHARED driver
// (LibreHardwareMonitor, Fan Control and OpenRGB can use it); delete this procedure
// if you would rather leave it for those tools.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
begin
  if CurUninstallStep <> usUninstall then Exit;

  if FileExists(ExpandConstant('{app}\PawnIO_setup.exe')) then
    Exec(ExpandConstant('{app}\PawnIO_setup.exe'), '-uninstall -silent', '',
      SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

// Runs right before files are copied. Closes the running app and OpenRGB so their
// executables — and OpenRGB's loaded WinRing0 kernel driver — are not locked while
// Setup replaces them. Without this, an upgrade over a running install fails with
// "Access is denied" on PcStatsMonitor.exe or OpenRGB\WinRing0x64.sys.
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
begin
  Exec('taskkill.exe', '/F /IM PcStatsMonitor.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec('taskkill.exe', '/F /IM OpenRGB.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  // Stop the WinRing0 kernel service so the kernel unloads the driver and releases
  // its .sys file (OpenRGB registers WinRing0 under this default name).
  Exec('sc.exe', 'stop WinRing0_1_2_0', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Sleep(1500);
  Result := '';
end;

